version: "3.5"
services:
  on-board-projectapi:
      container_name: on-board-projectapi
      build: ./server
      tty: true
      restart: always
      volumes:
        - ./server/:/app
      depends_on:
        - on-board-projectdb
      ports:
        - 8080:8080
      environment:
        PORT: 8080
        
        DRIVER: "postgres"
        DATABASE_URL: "host=on-board-projectdb user=postgres dbname=postgres password=postgres sslmode=disable"
        
      command: sh ./build.sh
  
  on-board-projectdb:
      image: postgres:10-alpine
      container_name: on-board-projectdb
      ports:
        - 3306:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGPASSWORD: postgres
        POSTGRES_DB: postgres
        DATABASE_HOST: localhost
      command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
      logging:
        options:
          max-size: "10k"
          max-file: "5"
      volumes:
        - ./server/config/database/init:/docker-entrypoint-initdb.d
  
